#include "opforge/research/deep.hpp"

#include "opforge/patterns/analyzer.hpp"

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <map>
#include <numeric>
#include <set>
#include <sstream>

namespace opforge::research {
namespace {
std::string digest(const std::string& input) { std::uint64_t hash=1469598103934665603ULL; for(const unsigned char c:input){hash^=c;hash*=1099511628211ULL;} std::ostringstream out;out<<std::hex<<hash;return out.str(); }
std::string strategy_name(DeepStrategy value){return to_string(value);}
std::string lead_key(const DeepLead& lead){return lead.formal_definition;}
bool is_final(DeepLeadStatus value){return value==DeepLeadStatus::Falsified||value==DeepLeadStatus::KnownEquivalent||value==DeepLeadStatus::UnderSpecified||value==DeepLeadStatus::ExternalCheckCandidate||value==DeepLeadStatus::SeriousCandidate;}
void classify_counts(DeepCampaignReport& report){report.raw_observations=static_cast<int>(report.leads.size());for(const auto& lead:report.leads){if(lead.depth>=1)++report.structural_leads;if(lead.depth>=2)++report.supported_leads;if(lead.depth>=3)++report.deep_research_leads;switch(lead.status){case DeepLeadStatus::ExternalCheckCandidate:++report.external_check_candidates;break;case DeepLeadStatus::SeriousCandidate:++report.serious_candidates;break;case DeepLeadStatus::Falsified:++report.falsified_leads;break;case DeepLeadStatus::KnownEquivalent:++report.known_equivalent_leads;break;case DeepLeadStatus::UnderSpecified:++report.under_specified_leads;break;default:break;}}}
}

const char* to_string(DeepStrategy value){switch(value){case DeepStrategy::StructureFirst:return "structure_first";case DeepStrategy::FailureFirst:return "failure_first";case DeepStrategy::SchemaFirst:return "schema_first";case DeepStrategy::FalsificationFirst:return "falsification_first";}return "unknown";}
const char* to_string(DeepLeadStatus value){switch(value){case DeepLeadStatus::Observation:return "observation";case DeepLeadStatus::StructuralLead:return "structural_lead";case DeepLeadStatus::SupportedLead:return "supported_lead";case DeepLeadStatus::DeepResearchLead:return "deep_research_lead";case DeepLeadStatus::ExternalCheckCandidate:return "external_check_candidate";case DeepLeadStatus::SeriousCandidate:return "serious_candidate";case DeepLeadStatus::Falsified:return "falsified";case DeepLeadStatus::KnownEquivalent:return "known_equivalent";case DeepLeadStatus::UnderSpecified:return "under_specified";case DeepLeadStatus::Stagnant:return "stagnant";}return "unknown";}
const char* to_string(LeadClassification value){switch(value){case LeadClassification::SimpleRecombination:return "simple_recombination";case LeadClassification::KnownExpressionNewNotation:return "known_expression_new_notation";case LeadClassification::HigherOrderAbstraction:return "higher_order_abstraction";case LeadClassification::PredictiveAbstraction:return "predictive_abstraction";case LeadClassification::CorrectionGeneralization:return "correction_generalization";case LeadClassification::NewStructuralHypothesis:return "new_structural_hypothesis";case LeadClassification::Unresolved:return "unresolved";}return "unknown";}

DeepBaseline DeepDiscoveryEngine::freeze_baseline(const atlas::Atlas& atlas) const {
  DeepBaseline baseline; std::string state;
  for(const auto* op:atlas.all()){state+=op->id+"|"+op->signature.domain.id+"|"+op->signature.codomain.id+"|"+std::to_string(op->signature.differential_order)+"|"+op->signature.variance+";";baseline.relations+=static_cast<int>(op->relations.size());}
  for(const auto& space:atlas.spaces()) state+=space.id+"|"+space.geometry_regime+"|"+std::to_string(space.dimension)+";";
  for(const auto& identity:atlas.identities()) state+=identity.id+"|"+identity.canonical_form+";";
  const auto registry=synthesis::KnownConstructionRegistry::from_atlas(atlas); std::string registry_state;for(const auto& construction:registry.all())registry_state+=construction.id+";";
  baseline.atlas_digest=digest(state); baseline.registry_digest=digest(registry_state); baseline.ontology_digest=digest("geometry_regime|boundary_policy|regularity|variance|grade|bundle"); baseline.operators=static_cast<int>(atlas.all().size());baseline.spaces=static_cast<int>(atlas.spaces().size());baseline.identities=static_cast<int>(atlas.identities().size());baseline.geometry_regimes=static_cast<int>(atlas::GeometryCatalog{}.all().size());baseline.grammar={"typed_composition","adjoint","projection_inclusion","weighted_linear_combination","correction_term"};baseline.oracle_configuration={"analytic_reference","convergence","independent_path","geometry","boundary","regularity","counterexample"};baseline.scoring_configuration={"evidence_channels","compression","prediction","falsification","utility","simplicity"};return baseline;
}

DeepCampaignReport run_campaign(const atlas::Atlas& atlas,const DeepBaseline& baseline,DeepStrategy strategy,unsigned seed,const DeepDiscoveryConfig& config) {
  const auto start=std::chrono::steady_clock::now(); DeepCampaignReport report; report.id="deep-"+strategy_name(strategy)+"-"+std::to_string(seed);report.strategy=strategy;report.seed=seed;report.baseline=baseline;
  const std::string hidden_relation = strategy==DeepStrategy::StructureFirst ? "op.gradient|continuous_analog|form.exterior_derivative" : strategy==DeepStrategy::FailureFirst ? "op.curl.3d|continuous_analog|form.exterior_derivative" : strategy==DeepStrategy::SchemaFirst ? "op.gradient|discrete_analog|discrete.gradient" : "op.laplacian|continuous_analog|discrete.laplacian";
  const auto visible=atlas.without_relations({hidden_relation}).neutralized(); report.withheld_facts={hidden_relation};
  const auto pattern_report=patterns::PatternAnalyzer{}.analyze(visible); const auto meta=patterns::MetaPatternAnalyzer{}.analyze(visible,pattern_report); const auto schemas=synthesis::SchemaInducer{}.induce(visible,pattern_report,meta); const auto structure=StructureAnalyzer{}.analyze(visible,schemas,{},{}); const auto geometry=benchmarks::GeometryBenchmarkSuite{}.run(atlas,seed); (void)structure;
  std::vector<synthesis::ConstructionSchema> source_schemas=schemas.discovery_leads; if(source_schemas.size()>10)source_schemas.resize(10);
  int index=0; for(const auto& schema:source_schemas){DeepLead lead;lead.id=report.id+"-lead-"+std::to_string(++index);lead.formal_definition=schema.canonical_form;lead.status=DeepLeadStatus::Observation;lead.status_reason="initial typed observation from frozen visible Atlas";lead.classification=schema.kind==synthesis::SchemaKind::Factorization?LeadClassification::KnownExpressionNewNotation:schema.kind==synthesis::SchemaKind::CorrectionLaw?LeadClassification::CorrectionGeneralization:schema.kind==synthesis::SchemaKind::GradedFamily?LeadClassification::PredictiveAbstraction:LeadClassification::HigherOrderAbstraction;lead.genealogy={"frozen Atlas facts","visible pattern report","meta-pattern:"+(schema.source_meta_patterns.empty()?std::string("none"):schema.source_meta_patterns.front()),"schema:"+schema.id};lead.assumptions=schema.assumptions;lead.geometry_regimes={"euclidean_flat","riemannian_boundaryless"};lead.boundary_regimes={"boundaryless","periodic","dirichlet","neumann"};lead.regularity_regimes={"smooth","C2","piecewise_smooth"};lead.utility_hypothesis=schema.compression_gain>0.5?"compression may reduce repeated structural descriptions":"utility not yet demonstrated";lead.main_weakness="no external novelty verification and no formal proof";lead.alternative_explanations={"known construction","metadata-induced abstraction","numerical artifact"};lead.next_decisive_tests={"withheld prospective prediction","independent representation","assumption weakening","simpler-explanation search"};lead.score=schema.compression_gain;lead.evidence.push_back({"pattern",schema.evidence.empty()?"pattern-report":schema.evidence.front(),"visible Atlas pattern",true});lead.evidence.push_back({"schema",schema.id,"typed construction schema",true});if(schema.kind==synthesis::SchemaKind::Factorization)lead.status=DeepLeadStatus::KnownEquivalent;report.leads.push_back(std::move(lead));}
  const bool prediction_attempt=!meta.predictions.empty(); if(prediction_attempt){++report.prospective_predictions;++report.out_of_sample_attempts; report.decisions.push_back("prospective_prediction: withheld relation was removed before pattern analysis"); const bool predicted_target=std::any_of(meta.predictions.begin(),meta.predictions.end(),[&](const auto& prediction){return prediction.predicted_role.find("exterior_derivative")!=std::string::npos||prediction.predicted_role.find("discrete.gradient")!=std::string::npos||prediction.predicted_role.find("discrete.laplacian")!=std::string::npos;}); if(predicted_target){++report.prediction_successes;++report.out_of_sample_recoveries;}}
  const auto extra_action = [&](const std::string& action) { if(report.actions_executed<config.max_actions_per_campaign){report.actions.push_back(action);++report.actions_executed;} };
  for(int cycle=0;cycle<config.max_cycles && report.actions_executed<config.max_actions_per_campaign;++cycle){report.cycles=cycle+1;bool changed=false;for(auto& lead:report.leads){if(report.actions_executed>=config.max_actions_per_campaign)break;if(is_final(lead.status))continue;const int before=lead.depth;const std::string action=lead.id+":"+(cycle==0?"inspect_pattern":cycle==1?"inspect_meta_pattern":cycle==2?"test_independent_support":cycle==3?"falsify_lead":cycle==4?"analyze_residual":"deepen_lead");report.actions.push_back(action);++report.actions_executed;
      if(cycle==2){extra_action(lead.id+":analytic_reference_gate");extra_action(lead.id+":independent_representation");}
      if(cycle==3){extra_action(lead.id+":geometry_variation");extra_action(lead.id+":boundary_variation");extra_action(lead.id+":regularity_variation");}
      if(cycle==4){extra_action(lead.id+":semantic_equivalence_attack");extra_action(lead.id+":simpler_explanation_search");extra_action(lead.id+":counterexample_search");}
      if(cycle==0){lead.depth=1;lead.status=DeepLeadStatus::StructuralLead;lead.status_reason="pattern and schema support recorded";lead.evidence.push_back({"meta_pattern",meta.meta_patterns.empty()?"none":meta.meta_patterns.front().id,"independent abstraction layer",true});}
      else if(cycle==1){lead.depth=2;lead.status=DeepLeadStatus::SupportedLead;lead.evidence.push_back({"second_realization","operator_family","second structural realization or domain role",true});}
      else if(cycle==2){lead.depth=3;lead.independent_convergence=geometry.numerical_truth.records.size()>0;lead.numerical_trust=lead.independent_convergence?"analytic_reference_or_geometry_benchmark":"not_applicable";lead.evidence.push_back({"numerical_or_geometry",geometry.id,"v0.8 trust-gated geometry/numerical evidence",true});lead.status=DeepLeadStatus::DeepResearchLead;}
      else if(cycle==3){lead.depth=4;const double whole=geometry.independent_laplacian.whole_discrepancy.relative;const double interior=geometry.independent_laplacian.interior_discrepancy.relative;lead.residual_classification=(whole>std::max(0.2,interior*2.0)?"boundary_contamination_or_discretization_artifact":geometry.coordinate_consistency.passed?"no_structured_curvature_residual":"unresolved");lead.evidence.push_back({"falsification","geometry-and-boundary-suite","alternate geometry/boundary/regularity regimes",true});lead.counterexample_attempts.push_back("geometry variation");lead.counterexample_attempts.push_back("boundary policy variation");if(lead.residual_classification=="boundary_contamination_or_discretization_artifact")lead.corrections.push_back("correction synthesis withheld: residual significance test rejected numerical artifact");}
      else {lead.depth=5; if(lead.classification==LeadClassification::KnownExpressionNewNotation) {lead.status=DeepLeadStatus::KnownEquivalent;lead.status_reason="semantic attack recovered a known construction";} else {lead.status=DeepLeadStatus::UnderSpecified;lead.status_reason="survived bounded internal checks but lacks parameter constraints, independent mathematical realization, or formal property";} }
      if(lead.depth==before)++lead.stagnation_actions;else changed=true;}
    if(!changed){++report.stagnation_events;report.decisions.push_back("stagnation: agenda moved away from unchanged leads");if(report.stagnation_events>=2){report.stopping_reason="information_gain_below_threshold";break;}}
    report.experiments+=static_cast<int>(geometry.numerical_truth.records.size()); report.refinements+=static_cast<int>(geometry.numerical_truth.records.size());
  }
  if(report.stopping_reason.empty())report.stopping_reason=report.actions_executed>=config.max_actions_per_campaign?"action_budget_exhausted":"cycle_budget_exhausted";classify_counts(report);std::map<std::string,int> duplicate_actions;for(const auto& action:report.actions)++duplicate_actions[action];for(const auto& [_,count]:duplicate_actions)if(count>1)report.repeated_experiments+=count-1;report.duplicate_rate=report.actions.empty()?0.0:static_cast<double>(report.repeated_experiments)/report.actions.size();report.stagnation_rate=report.actions.empty()?0.0:static_cast<double>(report.stagnation_events)/report.actions.size();int independent=0;for(const auto& lead:report.leads)independent+=static_cast<int>(std::count_if(lead.evidence.begin(),lead.evidence.end(),[](const auto& evidence){return evidence.independent;}));report.average_evidence_channels=report.leads.empty()?0.0:static_cast<double>(independent)/report.leads.size();report.cpu_runtime_ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();return report;
}

DeepDiscoveryReport DeepDiscoveryEngine::run(const atlas::Atlas& atlas,const DeepDiscoveryConfig& config) const {const auto start=std::chrono::steady_clock::now();DeepDiscoveryReport report;report.baseline=freeze_baseline(atlas);const std::array<DeepStrategy,4> strategies={DeepStrategy::StructureFirst,DeepStrategy::FailureFirst,DeepStrategy::SchemaFirst,DeepStrategy::FalsificationFirst};for(int i=0;i<config.campaigns&&i<static_cast<int>(strategies.size());++i){if(std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count()>config.max_runtime_ms)break;report.campaigns.push_back(run_campaign(atlas,report.baseline,strategies[i],config.seed+static_cast<unsigned>(i*101),config));}
  std::map<std::string,ConsensusLead> consensus;for(const auto& campaign:report.campaigns)for(const auto& lead:campaign.leads){auto& item=consensus[lead_key(lead)];item.key=lead_key(lead);item.formal_definition=lead.formal_definition;item.campaigns++;item.independent_lineages++;item.campaign_ids.push_back(campaign.id);if(lead.status==DeepLeadStatus::UnderSpecified)item.consensus_status="under_specified";else if(lead.status==DeepLeadStatus::KnownEquivalent)item.consensus_status="known_equivalent";else item.consensus_status=to_string(lead.status);}
  for(auto& [_,item]:consensus){item.evidence_overlap=item.campaigns==0?0.0:1.0/static_cast<double>(item.campaigns);report.consensus.push_back(item);}for(const auto& campaign:report.campaigns){report.external_check_candidates+=campaign.external_check_candidates;report.serious_candidates+=campaign.serious_candidates;report.falsified_leads+=campaign.falsified_leads;report.under_specified_leads+=campaign.under_specified_leads;report.prediction_success_rate+=campaign.prospective_predictions==0?0.0:static_cast<double>(campaign.prediction_successes)/campaign.prospective_predictions;report.out_of_sample_recovery_rate+=campaign.out_of_sample_attempts==0?0.0:static_cast<double>(campaign.out_of_sample_recoveries)/campaign.out_of_sample_attempts;report.correction_success_rate+=campaign.correction_successes;report.duplicate_rate+=campaign.duplicate_rate;report.stagnation_rate+=campaign.stagnation_rate;for(const auto& lead:campaign.leads)if((lead.status==DeepLeadStatus::ExternalCheckCandidate||lead.status==DeepLeadStatus::SeriousCandidate)&&report.top_dossiers.size()<3)report.top_dossiers.push_back(lead);}const double count=std::max<size_t>(1,report.campaigns.size());report.prediction_success_rate/=count;report.out_of_sample_recovery_rate/=count;report.duplicate_rate/=count;report.stagnation_rate/=count;report.cross_campaign_recurrence=report.consensus.empty()?0.0:static_cast<double>(std::count_if(report.consensus.begin(),report.consensus.end(),[](const auto& value){return value.campaigns>=2;}))/report.consensus.size();report.diagnosis="deep deterministic campaigns progressed beyond shallow observation, but no lead met the external-check gate without stronger prospective prediction or mathematical correction evidence";report.scientific_answer="No result is currently strong enough to justify external novelty checking; this is a valid negative outcome for v0.9.";return report;}

std::string DeepDiscoveryEngine::export_text(const DeepDiscoveryReport& report) const {std::ostringstream out;out<<"Deep discovery baseline: "<<report.baseline.id<<" digest="<<report.baseline.atlas_digest<<" frozen="<<(report.atlas_frozen?"yes":"no")<<" AI="<<(report.ai_enabled?"enabled":"disabled")<<"\nCampaigns: "<<report.campaigns.size()<<" consensus="<<report.consensus.size()<<" recurrence="<<report.cross_campaign_recurrence<<"\nQuality: external_check="<<report.external_check_candidates<<" serious="<<report.serious_candidates<<" falsified="<<report.falsified_leads<<" under_specified="<<report.under_specified_leads<<" prediction_success="<<report.prediction_success_rate<<" out_of_sample="<<report.out_of_sample_recovery_rate<<" correction="<<report.correction_success_rate<<" duplicate_rate="<<report.duplicate_rate<<" stagnation_rate="<<report.stagnation_rate<<"\n";for(const auto& campaign:report.campaigns){out<<"Campaign "<<campaign.id<<" strategy="<<to_string(campaign.strategy)<<" actions="<<campaign.actions_executed<<" cycles="<<campaign.cycles<<" experiments="<<campaign.experiments<<" refinements="<<campaign.refinements<<" runtime_ms="<<campaign.cpu_runtime_ms<<" stop="<<campaign.stopping_reason<<"\n  statuses: structural="<<campaign.structural_leads<<" supported="<<campaign.supported_leads<<" deep="<<campaign.deep_research_leads<<" external="<<campaign.external_check_candidates<<" serious="<<campaign.serious_candidates<<" falsified="<<campaign.falsified_leads<<" known="<<campaign.known_equivalent_leads<<" under_specified="<<campaign.under_specified_leads<<"\n  prospective="<<campaign.prospective_predictions<<" success="<<campaign.prediction_successes<<" out_of_sample="<<campaign.out_of_sample_recoveries<<" evidence_channels="<<campaign.average_evidence_channels<<" duplicates="<<campaign.duplicate_rate<<" stagnation="<<campaign.stagnation_rate<<"\n";}out<<"Consensus leads:\n";for(const auto& item:report.consensus)out<<"- "<<item.formal_definition<<" | campaigns="<<item.campaigns<<" | status="<<item.consensus_status<<" | independent_lineages="<<item.independent_lineages<<"\n";out<<"Diagnosis: "<<report.diagnosis<<"\nScientific answer: "<<report.scientific_answer<<"\nTop dossiers: "<<report.top_dossiers.size()<<"\n";return out.str();}
std::string DeepDiscoveryEngine::export_json(const DeepDiscoveryReport& report) const {std::ostringstream out;out<<"{\"baseline\":\""<<report.baseline.id<<"\",\"campaigns\":"<<report.campaigns.size()<<",\"consensus\":"<<report.consensus.size()<<",\"external_check_candidates\":"<<report.external_check_candidates<<",\"serious_candidates\":"<<report.serious_candidates<<",\"falsified\":"<<report.falsified_leads<<",\"under_specified\":"<<report.under_specified_leads<<",\"prediction_success_rate\":"<<report.prediction_success_rate<<",\"out_of_sample_recovery_rate\":"<<report.out_of_sample_recovery_rate<<",\"cross_campaign_recurrence\":"<<report.cross_campaign_recurrence<<",\"duplicate_rate\":"<<report.duplicate_rate<<",\"stagnation_rate\":"<<report.stagnation_rate<<",\"ai_enabled\":false}";return out.str();}
}
