#include <algorithm>
#include <cassert>
#include <cmath>
#include <fstream>
#include "opforge/discovery/pipeline.hpp"
#include "opforge/discovery/composition.hpp"
#include "opforge/atlas/seed.hpp"
#include "opforge/patterns/analyzer.hpp"
#include "opforge/synthesis/candidate.hpp"
#include "opforge/research/evaluation.hpp"
#include "opforge/research/campaign.hpp"
#include "opforge/research/deep.hpp"
#include "opforge/axiomatic/engine.hpp"
#include "opforge/axiomatic/unknown.hpp"
#include "opforge/numerics/executor.hpp"
#include "opforge/numerics/truth.hpp"
#include "opforge/numerics/curved.hpp"
#include "opforge/atlas/loader.hpp"
#include "opforge/semantic/closure.hpp"
#include "opforge/analogy/engine.hpp"
#include "opforge/benchmarks/rediscovery.hpp"
int main() {
  opforge::atlas::Atlas a; opforge::atlas::OperatorRecord x{"x","X",""}; x.signature.domain.id="A"; x.signature.codomain.id="B";
  assert(a.add(x)); assert(!a.add(x)); assert(a.validate().empty());
  opforge::atlas::OperatorRecord bad{"bad","Bad",""}; bad.relations.push_back({opforge::atlas::RelationKind::RelatedTo,"missing","",""}); assert(a.add(bad)); assert(!a.validate().empty());
  assert(opforge::discovery::VerificationPipeline{}.verify(x,a).front().passed);
  opforge::atlas::Atlas v;
  v.add_space({"scalar.r3","ScalarField(R3)","R3","C2",3,-1,opforge::atlas::ScalarField::Real,true,false,false,true,false});
  v.add_space({"vector.r3","VectorField(R3)","R3","C1",3,-1,opforge::atlas::ScalarField::Real,true,false,false,true,false});
  opforge::atlas::OperatorRecord grad{"op.gradient","Gradient","grad"}; grad.signature.domain={"scalar.r3",""}; grad.signature.codomain={"vector.r3",""}; grad.signature.input_kind=opforge::atlas::ObjectKind::Scalar; grad.signature.output_kind=opforge::atlas::ObjectKind::Vector; grad.signature.differential_order=1; grad.signature.regularity="C2"; grad.signature.output_regularity="C1"; v.add(grad);
  opforge::atlas::OperatorRecord div{"op.divergence","Divergence","div"}; div.signature.domain={"vector.r3",""}; div.signature.codomain={"scalar.r3",""}; div.signature.input_kind=opforge::atlas::ObjectKind::Vector; div.signature.output_kind=opforge::atlas::ObjectKind::Scalar; div.signature.differential_order=1; div.signature.regularity="C1"; div.signature.output_regularity="C0"; v.add(div);
  auto composed=opforge::discovery::compose(div,grad,v); assert(composed.valid); assert(composed.signature.differential_order==2);
  auto too_smooth=div; too_smooth.signature.regularity="C2"; assert(!opforge::discovery::compose(too_smooth,grad,v).valid);
  auto wrong_order=opforge::discovery::compose(div,div,v); assert(!wrong_order.valid&&wrong_order.code=="space_mismatch");
  opforge::atlas::OperatorRecord curl{"curl","Curl","curl"}; curl.signature.domain={"vector.r3",""}; curl.signature.codomain={"vector.r3",""}; curl.signature.regularity="C1"; curl.signature.output_regularity="C0"; curl.signature.required_structures={"orientation"}; v.add(curl); auto no_orientation=opforge::discovery::compose(curl,grad,v); assert(!no_orientation.valid&&no_orientation.code=="missing_structure");
  opforge::atlas::OperatorRecord lap{"op.laplacian","Laplacian","Δ"}; lap.signature.domain={"scalar.r3",""}; lap.signature.codomain={"scalar.r3",""}; lap.signature.differential_order=2; lap.signature.regularity="C2"; v.add(lap);
  assert(opforge::discovery::RediscoveryEngine{}.discover(v).size()==1);
  assert(opforge::discovery::export_json(v).find("schema_version")!=std::string::npos);
  assert(opforge::discovery::export_graphviz(v).find("digraph Atlas")!=std::string::npos);

  auto seed=opforge::atlas::make_vector_calculus_seed();
  assert(seed.all().size()>=9); assert(seed.find("op.curl.3d")); assert(seed.find("op.rot.2d"));
  auto lap_trace=opforge::discovery::rediscover_div_grad(seed); assert(lap_trace.result=="rediscovered Laplacian"); assert(lap_trace.matched_operator=="op.laplacian");
  auto cg_trace=opforge::discovery::rediscover_curl_grad(seed); assert(cg_trace.result=="zero identity candidate");
  auto dc_trace=opforge::discovery::rediscover_div_curl(seed); assert(dc_trace.result=="zero identity candidate");
  assert(opforge::discovery::trace_text(lap_trace).find("Composition valid")!=std::string::npos);
  assert(opforge::discovery::trace_json(lap_trace).find("steps")!=std::string::npos);
  auto restored=opforge::discovery::import_json(opforge::discovery::export_json(seed)); assert(restored.all().size()==seed.all().size()); assert(restored.spaces().size()==seed.spaces().size());
  assert(opforge::atlas::derive_status({{"a","type_checked","","","","","","",-1}})==opforge::atlas::VerificationStatus::PartiallyVerified);
  assert(opforge::atlas::derive_status({{"a","formally_verified","","","","","","",-1}})==opforge::atlas::VerificationStatus::FormallyVerified);
  opforge::atlas::OperatorRecord claimed{"claimed","Claimed",""}; claimed.verification=opforge::atlas::VerificationStatus::FormallyVerified; seed.add(claimed); assert(claimed.verification==opforge::atlas::VerificationStatus::FormallyVerified); assert(seed.find("claimed")->verification==opforge::atlas::VerificationStatus::Proposed);
  auto invalid=opforge::discovery::infer(opforge::atlas::Expression::composition(opforge::atlas::Expression::ref("missing"),opforge::atlas::Expression::ref("op.gradient")),seed); assert(!invalid.valid&&invalid.code=="unknown_operator");
  auto dangling=opforge::atlas::Identity{"bad.identity","bad",opforge::atlas::Expression::ref("missing"),opforge::atlas::Expression::zero(),{}, {}, {}, {}, {}, opforge::atlas::VerificationStatus::Proposed,{}}; seed.add_identity(dangling); assert(!seed.validate().empty());
  auto report=opforge::patterns::PatternAnalyzer{}.analyze(opforge::atlas::make_vector_calculus_seed());
  bool complex=false, zero=false, chain=false; for(const auto& p:report.patterns){complex|=p.type==opforge::patterns::PatternType::DifferentialComplexCandidate; zero|=p.type==opforge::patterns::PatternType::ZeroComposition; chain|=p.type==opforge::patterns::PatternType::CompositionChain;}
  assert(complex&&zero&&chain); assert(!report.graph.empty()); assert(opforge::patterns::PatternAnalyzer{}.export_text(report).find("differential_complex_candidate")!=std::string::npos); assert(opforge::patterns::PatternAnalyzer{}.export_json(report).find("patterns")!=std::string::npos);
  opforge::atlas::Atlas renamed; renamed.add_space({"s0","S0","R3","C2",3,-1,opforge::atlas::ScalarField::Real,true,true,false,true,false}); renamed.add_space({"s1","S1","R3","C1",3,-1,opforge::atlas::ScalarField::Real,true,true,false,true,false}); renamed.add_space({"s2","S2","R3","C1",3,-1,opforge::atlas::ScalarField::Real,true,true,false,true,false}); renamed.add_space({"s3","S3","R3","C0",3,-1,opforge::atlas::ScalarField::Real,true,true,false,true,false});
  auto make=[&](const char* id,const char* d,const char* c){opforge::atlas::OperatorRecord r{id,id,""};r.signature.domain={d,""};r.signature.codomain={c,""};r.signature.regularity="C0";r.signature.output_regularity="C0";r.signature.differential_order=1;renamed.add(r);}; make("op_A","s0","s1");make("op_B","s1","s2");make("op_C","s2","s3");
  auto renamed_report=opforge::patterns::PatternAnalyzer{}.analyze(renamed); bool gap=false; for(const auto& p:renamed_report.patterns) gap|=p.type==opforge::patterns::PatternType::MissingLinkCandidate; assert(!renamed_report.graph.empty()&&gap);
  auto candidate_report=opforge::synthesis::CandidateSynthesizer{}.synthesize(seed,report); assert(!candidate_report.accepted.empty()); assert(!candidate_report.rejected.empty());
  auto candidate_report_again=opforge::synthesis::CandidateSynthesizer{}.synthesize(seed,report); assert(candidate_report.accepted.front().id==candidate_report_again.accepted.front().id);
  auto req=opforge::synthesis::OperatorRequirements{{"vector.r3",""},{"vector.r3",""},2,true,true,{"metric","orientation"},{}, {}};
  auto req_report=opforge::synthesis::CandidateSynthesizer{}.synthesize(seed,req,"explicit.requirement"); assert(!req_report.accepted.empty());
  auto c=req_report.accepted.front(); assert(!c.canonical_form.empty()); assert(!opforge::synthesis::is_trivial(c.expression,seed)); assert(opforge::synthesis::CandidateSynthesizer{}.export_json(candidate_report).find("accepted")!=std::string::npos); assert(!opforge::synthesis::ready_for_numerical_verification(c)); c.equivalence.equivalent=false; c.completion_ready=true; c.verification=opforge::atlas::VerificationStatus::SymbolicallyVerified; assert(opforge::synthesis::ready_for_numerical_verification(c));
  c.verification=opforge::atlas::VerificationStatus::Proposed; auto before=seed.all().size(); assert(!opforge::synthesis::CandidateSynthesizer{}.promote(seed,c)); c.verification=opforge::atlas::VerificationStatus::SymbolicallyVerified; assert(opforge::synthesis::CandidateSynthesizer{}.promote(seed,c)); assert(seed.all().size()==before+1);
  auto pass_property=opforge::research::Property{"P-pass","always zero",{}, {},{},1e-9,[](const opforge::research::TestCase&){return 0.0;}};
  auto fail_property=opforge::research::Property{"P-fail","always fails",{}, {},{},1e-9,[](const opforge::research::TestCase& tc){return tc.id=="zero"?1.0:0.0;}};
  auto eval_atlas=opforge::atlas::make_vector_calculus_seed();
  auto eval=opforge::research::CandidateEvaluationEngine{}.evaluate(eval_atlas,c,{pass_property},nullptr,{10,8,8,8,1000}); assert(eval.state==opforge::research::CandidateState::NumericallySupported); assert(eval.epistemic_status=="numerically_supported");
  auto failed_eval=opforge::research::CandidateEvaluationEngine{}.evaluate(eval_atlas,c,{fail_property},nullptr,{10,8,8,8,1000}); assert(failed_eval.state==opforge::research::CandidateState::CounterexampleRejected); assert(!failed_eval.counterexamples.empty());
  auto ce=opforge::research::CounterexampleSearchEngine{}.search(pass_property,c,{10,8,8,8,1000},42); assert(ce.status==opforge::research::ExperimentStatus::Inconclusive); auto ce2=opforge::research::CounterexampleSearchEngine{}.search(fail_property,c,{10,8,8,8,1000},42); assert(ce2.status==opforge::research::ExperimentStatus::Fail);
  auto budget_eval=opforge::research::CandidateEvaluationEngine{}.evaluate(eval_atlas,c,{},nullptr,{0,0,0,0,0}); assert(budget_eval.epistemic_status=="unknown");
  auto reports_seq=opforge::research::CandidateEvaluationEngine{}.evaluate_all(eval_atlas,candidate_report.accepted,{10,8,8,8,1000},false); auto reports_par=opforge::research::CandidateEvaluationEngine{}.evaluate_all(eval_atlas,candidate_report.accepted,{10,8,8,8,1000},true); assert(reports_seq.size()==reports_par.size()); for(size_t i=0;i<reports_seq.size();++i){assert(reports_seq[i].candidate_id==reports_par[i].candidate_id);assert(reports_seq[i].epistemic_status=="search_only_numeric_verification_blocked");assert(reports_seq[i].counterexamples.empty());}
  auto bench=opforge::research::BenchmarkEngine{}.compare(c,&c,opforge::research::canonical_test_cases(0,3),{10,8,8,8,1000}); assert(bench.status==opforge::research::ExperimentStatus::Pass); assert(bench.comparison!="structural proxy only; numerical executor unavailable");
  opforge::research::RejectedCandidateRecord rejected{c.id,c.canonical_form,"counterexample",failed_eval.experiments,{}}; assert(!rejected.rejection_reason.empty()); assert(opforge::research::CandidateEvaluationEngine{}.export_text(eval).find("Candidate")!=std::string::npos); assert(opforge::research::CandidateEvaluationEngine{}.export_json(eval).find("epistemic_status")!=std::string::npos);
  opforge::numerics::Grid grid{3,5,5,5,.1}; auto scalar=opforge::numerics::scalar_grid(grid,[](double x,double y,double z){return x+y+z;}); auto numerical=opforge::numerics::NumericalExecutor{}.apply("op.gradient",scalar,7); assert(numerical.supported); int center=((2*grid.ny+2)*grid.nx+2)*3; assert(std::abs(numerical.output.values[center]-1.0)<1e-9); assert(numerical.seed==7);
  auto campaign=opforge::research::ResearchOrchestrator{}.run(eval_atlas,opforge::research::CampaignMode::StructuralExploration,{2,10,50,10000}); assert(campaign.state.cycle>0); assert(!campaign.memory.discovered_patterns.empty()); assert(!campaign.actions.empty()); assert(opforge::research::ResearchOrchestrator{}.report_json(campaign).find("campaign_id")!=std::string::npos); assert(campaign.numerical_experiments==0); assert(campaign.geometry_benchmark.numerical_truth.records.empty()); auto bounded=opforge::patterns::PatternAnalyzer{}.analyze(eval_atlas,{1,1,1}); assert(bounded.truncated&&bounded.graph.size()<=1&&bounded.patterns.size()<=1);
  const std::string checkpoint="/tmp/opforge-test-checkpoint.txt"; assert(opforge::research::ResearchOrchestrator{}.save_checkpoint(checkpoint,campaign.state,campaign.memory)); auto loaded=opforge::research::ResearchOrchestrator{}.load_checkpoint(checkpoint); assert(loaded.first.id==campaign.state.id); assert(loaded.second.discovered_patterns.size()==campaign.memory.discovered_patterns.size()); assert(loaded.second.generated_candidates.size()==campaign.memory.generated_candidates.size()); auto resumed=opforge::research::ResearchOrchestrator{}.run(eval_atlas,opforge::research::CampaignMode::StructuralExploration,{4,10,50,10000},loaded.second,loaded.first,checkpoint); assert(resumed.evaluations.empty());
  const std::string memory_file="/tmp/opforge-test-memory.txt"; assert(campaign.memory.save(memory_file)); auto loaded_memory=opforge::research::ResearchMemory::load(memory_file); assert(loaded_memory.has(campaign.memory.discovered_patterns.front()));
  auto convergence=opforge::numerics::validate_seed_backend(); assert(convergence.size()==4); for(const auto& result:convergence)assert(result.passed);
  auto truth=opforge::numerics::NumericalTruthValidator{}.validate_core(16,17); assert(truth.records.size()==6); for(const auto& record:truth.records){assert(!record.analytic_reference.empty());assert(!record.convergence.empty());assert(record.boundary_validated);}
  auto curved_executor=opforge::numerics::CurvedGeometryExecutor{}; auto curved_cases=curved_executor.reference_suite(); assert(curved_cases.size()==3); for(const auto& geometry:curved_cases){auto curved_result=curved_executor.laplace_beltrami(geometry,{2,16,16,1,1.0/15.0});assert(curved_result.supported);assert(curved_result.analytic_error<0.5);} auto coordinates=curved_executor.coordinate_consistency({2,16,16,1,1.0/15.0});assert(coordinates.passed); auto covariant=curved_executor.covariant_derivative(curved_cases.back().metric,{{[](double x,double){return x*x;},[](double,double y){return y*y;}}},.4,.4); double connection_signal=0;for(const auto value:covariant)connection_signal+=std::abs(value);assert(connection_signal>0);
  auto hidden_report=opforge::benchmarks::HistoricalRediscovery{}.run(eval_atlas,{{"laplacian_rediscovery","hide Laplacian identity",{"identity.laplacian"},{"op.gradient","op.divergence"},{"identity.laplacian"},100},{"zero_composition","hide zero identity",{"identity.curl.grad.zero"},{"op.gradient","op.curl.3d"},{"identity.curl.grad.zero"},100},{"chain_complex","hide classification",{}, {"op.gradient","op.curl.3d","op.divergence"},{},100}}); assert(hidden_report.score.structural>=2); assert(hidden_report.score.partial>=1); assert(opforge::benchmarks::HistoricalRediscovery{}.export_json(hidden_report).find("recall")!=std::string::npos);
  auto expanded=opforge::atlas::AtlasLoader::load("atlas");
  auto neutralized=expanded.neutralized(); assert(!neutralized.find("form.exterior_derivative")); assert(!neutralized.find_identity("id.forms.d_squared")); assert(!neutralized.all().empty()); for(const auto* record:neutralized.all()) assert(record->symbol.empty()&&record->name.rfind("operator_",0)==0);
  auto expanded_benchmarks=std::vector<opforge::benchmarks::RediscoveryCase>{
    {"d_squared_abstraction","hide d-squared identity",{"id.forms.d_squared"},{"form.exterior_derivative","form.zero"},{"form.exterior_derivative|annihilates|form.zero"},100,true},
    {"hodge_decomposition","hide Hodge decomposition identity",{"id.forms.hodge_laplacian"},{"form.hodge_star","form.codifferential","form.de_rham_laplacian"},{"form.de_rham_laplacian|decomposition|form.exterior_derivative"},100,true},
    {"fourier_convolution","hide convolution theorem",{"id.transform.convolution_theorem"},{"transform.fourier","transform.inverse_fourier","transform.convolution"},{"transform.convolution|transform_correspondence|transform.fourier"},100,true},
    {"continuous_discrete_analogy","hide continuous-discrete bridge",{"id.discrete.continuous_gradient"},{"op.gradient","discrete.gradient","op.laplacian","discrete.laplacian"},{"discrete.gradient|discrete_analog|op.gradient"},100,true},
    {"projection_decomposition","hide projection decomposition identity",{"id.linear.symmetric_skew"},{"la.projection","la.orthogonal_projection","la.symmetric_projection","la.skew_projection"},{"la.symmetric_projection|decomposition|la.skew_projection"},100,true}
  };
  auto deep_report=opforge::benchmarks::HistoricalRediscovery{}.run(expanded,expanded_benchmarks); assert(deep_report.score.partial>=5); assert(deep_report.score.structural==0); assert(deep_report.score.false_positive==0); assert(deep_report.score.leakage_events==0); assert(deep_report.score.recall==1.0); assert(opforge::benchmarks::HistoricalRediscovery{}.export_text(deep_report).find("Leakage events: 0")!=std::string::npos);
  auto eq=opforge::synthesis::classify_equivalence(opforge::atlas::Expression::ref("op.gradient"),opforge::atlas::Expression::ref("op.gradient"),eval_atlas); assert(eq==opforge::synthesis::EquivalenceLevel::Canonical||eq==opforge::synthesis::EquivalenceLevel::Syntactic);
  const std::string atlas_json="/tmp/opforge-atlas.json"; {std::ofstream out(atlas_json);out<<opforge::discovery::export_json(eval_atlas);} auto loaded_atlas=opforge::atlas::AtlasLoader::load(atlas_json); assert(loaded_atlas.all().size()==eval_atlas.all().size()); assert(opforge::atlas::AtlasLoader::stats(loaded_atlas).operators==eval_atlas.all().size());
  auto expanded_stats=opforge::atlas::AtlasLoader::stats(expanded); assert(expanded_stats.operators>=50); assert(expanded_stats.spaces>=25); assert(expanded_stats.relations>=20); assert(expanded_stats.identities>=5); assert(opforge::atlas::AtlasLoader::validate(expanded).empty()); auto audit=opforge::atlas::AtlasLoader::audit_v2(expanded); assert(audit.clean()); assert(audit.missing_identity_assumptions==0); assert(deep_report.score.total_patterns>0); assert(deep_report.score.accepted_matches==5);
  auto registry=opforge::synthesis::KnownConstructionRegistry::from_atlas(expanded); assert(registry.find("construction.grad_div")); assert(registry.find("construction.hessian"));
  auto hessian_expr=opforge::atlas::Expression::composition(opforge::atlas::Expression::ref("op.jacobian"),opforge::atlas::Expression::ref("op.gradient")); auto hessian_semantics=opforge::synthesis::compare_semantics(hessian_expr,expanded); assert(hessian_semantics.equivalent); assert(hessian_semantics.matched_id=="construction.hessian"); assert(hessian_semantics.level==static_cast<int>(opforge::synthesis::EquivalenceLevel::IdentityRewrite));
  auto interest=opforge::synthesis::calculate_interestingness(c,expanded,opforge::patterns::PatternAnalyzer{}.analyze(expanded)); assert(interest.total()>=0.0); assert(!interest.reasons.empty() || interest.total()==0.0);
  auto oracle_results=opforge::research::CounterexampleOracleEngine{}.run_all(c,expanded,{10,8,8,8,1000}); assert(oracle_results.size()==5);
  opforge::research::DeepDiscoveryConfig deep_config; deep_config.campaigns=2; deep_config.max_cycles=5; deep_config.max_actions_per_campaign=80; deep_config.max_runtime_ms=15000; auto deep_discovery_report=opforge::research::DeepDiscoveryEngine{}.run(expanded,deep_config); assert(deep_discovery_report.atlas_frozen&&!deep_discovery_report.ai_enabled); assert(deep_discovery_report.campaigns.size()==2); assert(deep_discovery_report.baseline.id=="v0.9-deep-discovery-baseline"); assert(deep_discovery_report.baseline.numerical_backend=="isolated-proof-stage-only"); assert(deep_discovery_report.consensus.size()>0); for(const auto& item:deep_discovery_report.consensus){ assert(item.campaigns<=static_cast<int>(deep_discovery_report.campaigns.size())); assert(item.independent_lineages<=item.campaigns); } assert(deep_discovery_report.external_check_candidates==0); for(const auto& campaign:deep_discovery_report.campaigns) assert(campaign.experiments==0); assert(deep_discovery_report.out_of_sample_recovery_rate>=0.0&&deep_discovery_report.out_of_sample_recovery_rate<=1.0); assert(opforge::research::DeepDiscoveryEngine{}.export_json(deep_discovery_report).find("prediction_success_rate")!=std::string::npos);
  auto structures=opforge::axiomatic::StructureLibrary{}.initial(); assert(structures.size()>=14); auto axiomatic_benchmarks=opforge::axiomatic::AxiomaticEngine{}.run_predictive_benchmarks(expanded); assert(axiomatic_benchmarks.benchmarks.size()==5); assert(axiomatic_benchmarks.successful_predictions==4); assert(axiomatic_benchmarks.out_of_sample_recoveries==4); assert(axiomatic_benchmarks.false_structures_rejected==1); auto axiomatic_ablation=opforge::axiomatic::AxiomaticEngine{}.run_ablation(expanded,axiomatic_benchmarks); assert(axiomatic_ablation.axiomatic_successes>axiomatic_ablation.pattern_only_successes); assert(axiomatic_ablation.axiomatic_precision==1.0);
  auto axiomatic_recognition=opforge::axiomatic::AxiomaticEngine{}.recognize(expanded.neutralized()); auto axiomatic_deduction=opforge::axiomatic::AxiomaticEngine{}.derive(expanded.neutralized(),axiomatic_recognition); assert(!axiomatic_recognition.recognized.empty()); assert(axiomatic_deduction.dag.acyclic&&axiomatic_deduction.dag.leakage_free); assert(!axiomatic_deduction.predictions.empty()); assert(opforge::axiomatic::AxiomaticEngine{}.export_json(opforge::axiomatic::AxiomaticEngine{}.run(expanded,{1,1,20,8000,31})).find("successful_predictions")!=std::string::npos);
  opforge::axiomatic::UnknownStructureEngine unknown_engine; auto unknown_stress=unknown_engine.stress_test_known_axioms(expanded); assert(unknown_stress.total_cases==14); assert(unknown_stress.held_out.successes==3); assert(unknown_stress.held_out.near_miss_rejections==1); assert(!unknown_stress.held_out_manifest_hash.empty()); auto unknown_report=unknown_engine.run(expanded,{1,3,40,12,8,4,16,8000,47}); assert(unknown_report.ai_enabled==false&&unknown_report.atlas_frozen); assert(unknown_report.synthetic_benchmarks.size()==4); assert(unknown_report.ablation.unknown_structure_successes==3); assert(unknown_report.harder_unseen_benchmark.candidate_axioms>=2&&unknown_report.harder_unseen_benchmark.predictions==2&&unknown_report.harder_unseen_benchmark.hold_one_relation_successes==2&&unknown_report.harder_unseen_benchmark.held_out_realization_success&&unknown_report.harder_unseen_benchmark.near_miss_rejected); assert(unknown_report.real_validation.withheld_facts==2&&unknown_report.real_validation.prediction_attempts==2); assert(unknown_report.atlas_expansion_ablation.atlas_b_operators>=expanded.all().size()); assert(unknown_report.under_specified_total>=0); assert(opforge::axiomatic::UnknownStructureEngine{}.export_json(unknown_report).find("harder_unseen_successes")!=std::string::npos);
  auto atlas_v012=opforge::atlas::AtlasLoader::load("atlas"); auto atlas_b_v012=opforge::atlas::AtlasLoader::load_excluding("atlas",{"semantic_densification_v013.json"}); auto v012_stats=opforge::atlas::AtlasLoader::stats(atlas_v012); assert(v012_stats.operators>=95&&v012_stats.spaces>=45&&v012_stats.relations>=90); assert(v012_stats.executable_equalities+v012_stats.semantic_statements==v012_stats.identities); const auto executable_identity_count=static_cast<int>(std::count_if(atlas_v012.identities().begin(),atlas_v012.identities().end(),[](const auto& identity){return identity.executable_equality;})); assert(executable_identity_count>0&&executable_identity_count<static_cast<int>(atlas_v012.identities().size())); const auto* convolution_statement=atlas_v012.find_identity("id.transform.convolution_theorem"); assert(convolution_statement&&!convolution_statement->executable_equality); const auto* laplacian_statement=atlas_v012.find_identity("atlas.identity.laplacian"); assert(laplacian_statement&&laplacian_statement->executable_equality); auto diversity=opforge::atlas::AtlasLoader::diversity(atlas_v012); assert(diversity.domains.size()>=10&&diversity.structure_kinds.size()>=20&&diversity.bridges_per_domain_pair.size()>=10); assert(diversity.algebraic_coverage&&diversity.geometric_coverage&&diversity.spectral_coverage&&diversity.variational_coverage&&diversity.discrete_coverage); assert(opforge::atlas::AtlasLoader::audit_v3(atlas_v012).clean());
  opforge::semantic::ConsequenceClosureEngine closure_engine; auto closure=closure_engine.close(atlas_v012,{2,80,0.05,true}); assert(closure.rules.size()>=8&&closure.accepted>0&&closure.duplicates>0&&closure.dag_acyclic); auto density=closure_engine.density(closure.closed_atlas,&closure); assert(density.derived_consequences==static_cast<size_t>(closure.accepted)&&density.connected_components>0&&density.cross_domain_edge_ratio>0.0); auto real_v2=closure_engine.run_real_benchmark_v2(atlas_v012,{2,80,0.05,true}); assert(real_v2.attempts>0&&real_v2.successes>0&&real_v2.leakage_failures==0); auto abc=closure_engine.run_abc_ablation(opforge::atlas::make_vector_calculus_seed(),atlas_b_v012,{1,40,0.05,true}); assert(abc.c.identities>abc.b.identities&&abc.c.derived_consequences>0&&abc.a.operators<abc.c.operators);
  opforge::analogy::StructuralAnalogyEngine analogy_engine; auto analogy_candidates=analogy_engine.discover(atlas_v012,{16,8,8,5,0.2,5000}); assert(!analogy_candidates.empty()&&analogy_candidates.front().role_mapping.size()>=2); auto transferred=analogy_engine.transfer(atlas_v012,analogy_candidates.front()); assert(!transferred.empty()); auto analogy_benchmarks=analogy_engine.run_benchmarks(atlas_v012,{16,8,8,8,0.2,5000}); assert(!analogy_benchmarks.empty()); auto negative_transfer=analogy_engine.run_negative_transfer_case(); assert(negative_transfer.negative_transfer_rejected&&!negative_transfer.residuals.empty());
  auto meta_report=opforge::patterns::MetaPatternAnalyzer{}.analyze(expanded,opforge::patterns::PatternAnalyzer{}.analyze(expanded)); assert(meta_report.objects.size()>0); assert(!meta_report.meta_patterns.empty()); assert(!meta_report.predictions.empty()); assert(opforge::patterns::MetaPatternAnalyzer{}.export_text(meta_report).find("Meta-patterns")!=std::string::npos);
  auto residual=opforge::research::ResidualAnalyzer{}.classify(c,"dimension","dimension generalization failure",1.0); auto residual_clusters=opforge::research::ResidualAnalyzer{}.cluster({residual}); assert(residual.cluster_key==opforge::research::ResidualAnalyzer{}.canonicalize(residual)); assert(residual_clusters.size()==1); assert(!residual_clusters.front().correction_requirements.empty());
  auto goals=opforge::synthesis::GoalDirectedSynthesizer{}.derive_goals(expanded,meta_report,residual_clusters); assert(!goals.empty()); assert(!opforge::synthesis::GoalDirectedSynthesizer{}.active_rules(expanded,goals.front()).empty());
  auto residual_benchmark=opforge::benchmarks::ResidualDrivenBenchmark{}.run(expanded); assert(residual_benchmark.failure_found&&residual_benchmark.residual_classified&&residual_benchmark.requirements_derived); assert(residual_benchmark.correction_found&&residual_benchmark.repaired);
  auto schema_discovery=opforge::synthesis::SchemaInducer{}.induce(expanded,opforge::patterns::PatternAnalyzer{}.analyze(expanded),meta_report); assert(!schema_discovery.schemas.empty()); assert(!schema_discovery.parameterized_families.empty()); assert(!schema_discovery.completions.empty()); assert(!schema_discovery.discovery_leads.empty()); assert(opforge::synthesis::SchemaInducer{}.export_text(schema_discovery).find("Schemas")!=std::string::npos);
  auto structure_analysis=opforge::research::StructureAnalyzer{}.analyze(expanded,schema_discovery,{residual},residual_clusters); assert(!structure_analysis.closures.empty()); assert(!structure_analysis.commutators.empty()); assert(opforge::research::StructureAnalyzer{}.export_text(structure_analysis).find("Commutators")!=std::string::npos);
  auto schema_benchmark=opforge::benchmarks::SchemaCompressionBenchmark{}.run(expanded); assert(schema_benchmark.inferred&&schema_benchmark.assumptions_preserved&&schema_benchmark.compression_gain>0.0);
  opforge::research::CampaignConfig open_config; open_config.campaign_id="C-test-open"; open_config.atlas_snapshot="v0.25-open-search-baseline"; open_config.budget={2,20,10,5000}; auto frozen_stats=opforge::atlas::AtlasLoader::stats(expanded); auto open_report=opforge::research::ResearchOrchestrator{}.run(expanded,open_config); auto after_stats=opforge::atlas::AtlasLoader::stats(expanded); assert(open_report.ai_enabled==false&&open_report.target=="none"&&open_report.atlas_frozen); assert(open_report.atlas_snapshot=="v0.25-open-search-baseline"); assert(open_report.state.cycle>0); assert(open_report.memory.discovered_patterns.size()>0); assert(open_report.unresolved.size()>0); assert(open_report.scientific.baseline.frozen&&open_report.scientific.leads.size()==17&&open_report.scientific.benchmarks.size()==12&&open_report.scientific.metrics.leakage==0); assert(after_stats.operators==frozen_stats.operators&&after_stats.relations==frozen_stats.relations); assert(open_report.numerical_experiments==0); assert(!open_report.geometry_diagnostics_ran); assert(opforge::research::ResearchOrchestrator{}.report_json(open_report).find("\"geometry_diagnostics_ran\":false")!=std::string::npos); auto verify_config=open_config; verify_config.campaign_id="C-test-proof-gate"; verify_config.enable_numerical_verification=true; auto verify_report=opforge::research::ResearchOrchestrator{}.run(expanded,verify_config); assert(verify_report.numerical_experiments==0); assert(!verify_report.geometry_diagnostics_ran);
  auto blind_cases=opforge::benchmarks::default_blind_rediscovery_cases(); auto blind_report=opforge::benchmarks::BlindRediscoveryHarness{}.run(expanded,blind_cases); assert(!blind_report.engine_knows_targets); assert(blind_report.score.leakage_events==0&&blind_report.score.invalid_benchmarks==0); assert(blind_report.score.numerical_experiments==0); assert(blind_report.score.false_positive==0&&blind_report.score.negative_control_pass==3); assert(blind_report.score.structural+blind_report.score.partial+blind_report.score.missed>=6); assert(opforge::benchmarks::BlindRediscoveryHarness{}.export_json(blind_report).find("\"engine_knows_targets\":false")!=std::string::npos);
  for(const auto& result:blind_report.results) assert(!result.candidate_id_digest.empty());
  auto blind_report_again=opforge::benchmarks::BlindRediscoveryHarness{}.run(expanded,blind_cases); assert(opforge::benchmarks::BlindRediscoveryHarness{}.export_json(blind_report)==opforge::benchmarks::BlindRediscoveryHarness{}.export_json(blind_report_again));
  auto scaling=opforge::benchmarks::ScalingRegression{}.run(expanded,50); assert(scaling.runs.size()==3); assert(scaling.runs[0].operators<scaling.runs[1].operators&&scaling.runs[1].operators<scaling.runs[2].operators); for(const auto& run:scaling.runs) assert(run.numerical_experiments==0&&run.maximum_retained_frontier==64&&run.operators>0); auto scaling_again=opforge::benchmarks::ScalingRegression{}.run(expanded,50); for(size_t i=0;i<scaling.runs.size();++i){assert(scaling.runs[i].operators==scaling_again.runs[i].operators);assert(scaling.runs[i].compatible_edges==scaling_again.runs[i].compatible_edges);assert(scaling.runs[i].raw_candidate_count==scaling_again.runs[i].raw_candidate_count);assert(scaling.runs[i].canonical_classes==scaling_again.runs[i].canonical_classes);assert(scaling.runs[i].pruned_candidates==scaling_again.runs[i].pruned_candidates);}
  bool unrestricted_linear_combination=false; for(const auto& candidate:candidate_report.accepted){unrestricted_linear_combination|=candidate.expression&& (candidate.expression->kind==opforge::atlas::Expression::Kind::Addition||candidate.expression->kind==opforge::atlas::Expression::Kind::ScalarMultiplication);} assert(!unrestricted_linear_combination); bool goal_directed_linear_rule=false; for(const auto& goal:goals) for(const auto rule:opforge::synthesis::GoalDirectedSynthesizer{}.active_rules(expanded,goal)) goal_directed_linear_rule|=rule==opforge::synthesis::GrammarRule::WeightedLinearCombination; assert(goal_directed_linear_rule); auto unsupported_probe=opforge::research::CounterexampleSearchEngine{}.search(opforge::research::Property{"P-unsupported","no executable property",{}, {},{},1e-9,{}},c,{10,8,8,8,1000},42); assert(unsupported_probe.status==opforge::research::ExperimentStatus::Unsupported&&unsupported_probe.reason.find("error function")!=std::string::npos); assert(opforge::research::ResearchOrchestrator{}.report_json(open_report).find("\"coordinate_consistency\":null")!=std::string::npos);
}
